apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/toysavi/argocd-awx.git
    targetRevision: main
    path: awx

  destination:
    server: https://kubernetes.default.svc
    namespace: awx

  syncPolicy:
    automated:
      selfHeal: true
      prune: false