apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx

spec:
  admin_user: admin
  admin_email: savi_toy@phillipbank.com.kh

  hostname: awx-uat.phillipbank.com.kh

  ingress_type: ingress
  ingress_annotations: |
    kubernetes.io/ingress.class: traefik

  ingress_tls_secret: awx-tls

  service_type: ClusterIP

  projects_persistence: true
  projects_storage_size: 10Gi

  replicas: 1